<?php 

//create callable function 

//$numArray is generated by another process
$numArray = array('13','14','33');

var_dump($numArray);

//my conversion function
function str_to_int($val){
  //remember: settype($x, 'int') returns boolean (1=success, 0=failure)
  //--> so return $x to return new value
    settype($val,'int');
    return $val;
}

$newArr=array_walk($numArray,'str_to_int');
echo "<pre>";
var_dump($newArr);
?>